"""
Compute the permutation group generated by the 2x2 corner rotations of an
m x n grid (cells labelled 1..m*n in row-major order), by brute-force BFS
over the Cayley graph. Used to check by direct computation whether these
rotations generate the full symmetric group S_{m*n}.

Convention matches initial_3cycle.tex: for a 2x2 block with top-left p,
top-right p+1, bottom-left q, bottom-right q+1 (q = p + n, n = grid width),
the generator is the true clockwise rotation (p, p+1, q+1, q), i.e.
top-left -> top-right -> bottom-right -> bottom-left -> top-left.
"""

from itertools import product
from collections import Counter
from math import factorial


def to_perm(cycles, size):
    p = list(range(1, size + 1))
    for cyc in cycles:
        for i in range(len(cyc)):
            src = cyc[i]
            dst = cyc[(i + 1) % len(cyc)]
            p[src - 1] = dst
    return tuple(p)


def compose(p, q):
    """Apply p then q (left to right), matching the doc's convention."""
    return tuple(q[p[i] - 1] for i in range(len(p)))


def grid_generators(rows, cols):
    """The (rows-1)*(cols-1) corner-rotation 4-cycles for an rows x cols grid."""
    size = rows * cols
    gens = []
    for r in range(rows - 1):
        for c in range(cols - 1):
            p = r * cols + c + 1
            q = p + cols
            gens.append(to_perm([[p, p + 1, q + 1, q]], size))
    return gens, size


def generate_group(gens, size):
    identity = tuple(range(1, size + 1))
    group = {identity}
    frontier = [identity]
    while frontier:
        new_frontier = []
        for g in frontier:
            for gen in gens:
                h = compose(g, gen)
                if h not in group:
                    group.add(h)
                    new_frontier.append(h)
        frontier = new_frontier
    return group


def cycle_type(p):
    n = len(p)
    seen = [False] * n
    lens = []
    for i in range(n):
        if not seen[i]:
            l = 0
            j = i
            while not seen[j]:
                seen[j] = True
                j = p[j] - 1
                l += 1
            lens.append(l)
    return tuple(sorted(lens))


def orbit(group, size, start=1):
    return sorted({g[start - 1] for g in group})


def report(rows, cols):
    gens, size = grid_generators(rows, cols)
    G = generate_group(gens, size)
    print(f"{rows}x{cols} grid: |G| = {len(G)}  (|S_{size}| = {factorial(size)})")
    print(f"  transitive: {len(orbit(G, size)) == size}")
    print(f"  full symmetric group: {len(G) == factorial(size)}")
    types = Counter(cycle_type(g) for g in G)
    for t, c in sorted(types.items()):
        print(f"    cycle type {t}: {c}")
    print()
    return G


def group_order(rows, cols):
    """Order of the grid rotation group via Schreier-Sims (sympy), not brute
    enumeration -- needed once the group is too big to list out (e.g. any
    m,n >= 3 with mn >= 9, or 2xn with n >= 5)."""
    from sympy.combinatorics import Permutation, PermutationGroup

    size = rows * cols
    gens = []
    for r in range(rows - 1):
        for c in range(cols - 1):
            p = r * cols + c + 1
            q = p + cols
            gens.append(Permutation([[p - 1, p, q, q - 1]], size=size))
    G = PermutationGroup(gens)
    return G.order(), G.is_transitive(), G.is_primitive()


def verify_2x4_elementary_proof():
    """Check every claim in the elementary (Jordan-free) proof that G_4 = S_8
    in the "n=4" subsection of initial_3cycle.tex: the mirror symmetry, the
    conjugation sweep giving (1,2,w) for all w, and the moving lemma."""
    (g1, g2, g3), _ = grid_generators(2, 4)

    def inv(p):
        r = [0] * len(p)
        for i, x in enumerate(p):
            r[x - 1] = i + 1
        return tuple(r)

    def conj(x, by):  # by^-1 x by
        return compose(compose(inv(by), x), by)

    def comm(s, t):
        return compose(compose(inv(s), inv(t)), compose(s, t))

    mu = to_perm([[1, 4], [2, 3], [5, 8], [6, 7]], 8)
    assert conj(g1, mu) == inv(g3), "mu^-1 g1 mu should be g3^-1"
    assert conj(g2, mu) == inv(g2), "mu^-1 g2 mu should be g2^-1"
    assert conj(g3, mu) == inv(g1), "mu^-1 g3 mu should be g1^-1"

    tau1 = comm(g1, g2)
    c234 = comm(tau1, g3)
    assert c234 == to_perm([[2, 3, 4]], 8), "[[g1,g2],g3] should be (2,3,4)"

    base = inv(conj(c234, mu))
    assert base == to_perm([[1, 2, 3]], 8), "mirror of (2,3,4), inverted, should be (1,2,3)"

    sweep = {3: base}
    cur = base
    for w in (4, 8, 7):
        cur = conj(cur, g3)
        sweep[w] = cur
    sweep[5] = conj(conj(base, inv(g1)), inv(g2))
    sweep[6] = conj(inv(base), inv(g2))
    for w in (3, 4, 5, 6, 7, 8):
        assert sweep[w] == to_perm([[1, 2, w]], 8), f"sweep failed at w={w}"

    tau2 = comm(g2, g3)
    assert tau2 == to_perm([[3, 4], [6, 7]], 8), "[g2,g3] should be (3,4)(6,7)"
    seed = comm(g1, tau2)
    assert seed == to_perm([[5, 6, 7]], 8), "[g1,[g2,g3]] should be (5,6,7)"

    stab1 = generate_group([g2, g3, seed], 8)
    assert all(p[0] == 1 for p in stab1), "stab1 should fix cell 1"
    assert {p[1] for p in stab1} == set(range(2, 9)), "stab1 should be transitive on {2,...,8}"

    print("All claims in the n=4 elementary proof verified.")


def verify_g3_iso_s5():
    """Check every claim in the Theorem 2 proof (Section 8, 'n=3' subsection)
    of initial_3cycle.tex that G_3 (the 2x3 grid rotation group) is
    isomorphic to S_5: trivial centre, derived subgroup of order 60 (index
    2, hence normal), and that derived subgroup simple via the
    conjugacy-class subset-sum argument (no nonempty subset of the nontrivial
    class sizes, plus 1 for the identity, is a proper nontrivial divisor of
    60). Does not re-derive the two classical inputs (A_5 is the unique
    simple group of order 60; Aut(A_5) = S_5) -- those are cited in the
    paper, not computed here."""
    from itertools import combinations

    gens, size = grid_generators(2, 3)
    G = list(generate_group(gens, size))
    assert len(G) == 120, f"|G_3| should be 120, got {len(G)}"

    identity = tuple(range(1, size + 1))

    def inv(p):
        r = [0] * len(p)
        for i, x in enumerate(p):
            r[x - 1] = i + 1
        return tuple(r)

    def comm(x, y):
        return compose(compose(inv(x), inv(y)), compose(x, y))

    central = [g for g in G if all(compose(g, h) == compose(h, g) for h in gens)]
    assert central == [identity], f"Z(G_3) should be trivial, got {central}"

    commutators = set(comm(x, y) for x in G for y in G)
    D = set(commutators) | {identity}
    frontier = list(D)
    while frontier:
        new_frontier = []
        for g in frontier:
            for c in commutators:
                h = compose(g, c)
                if h not in D:
                    D.add(h)
                    new_frontier.append(h)
        frontier = new_frontier
    assert len(D) == 60, f"derived subgroup should have order 60, got {len(D)}"
    assert len(G) // len(D) == 2, "derived subgroup should have index 2"

    # conjugacy classes of D, as a subgroup of S_6 in its own right
    D = list(D)
    seen = set()
    classes = []
    for g in D:
        if g in seen:
            continue
        cls = set(compose(compose(inv(h), g), h) for h in D)
        seen |= cls
        classes.append(cls)
    sizes = sorted(len(c) for c in classes)
    assert sizes == [1, 12, 12, 15, 20], f"D's conjugacy class sizes should be [1,12,12,15,20], got {sizes}"

    nontrivial = [12, 12, 15, 20]
    divisors = [d for d in range(1, 61) if 60 % d == 0]
    bad = []
    for r in range(0, len(nontrivial) + 1):
        for combo in combinations(nontrivial, r):
            total = 1 + sum(combo)
            if total in divisors and total not in (1, 60):
                bad.append((combo, total))
    assert not bad, f"D should be simple, but found candidate normal subgroup orders: {bad}"

    print("All claims in the G_3 ~= S_5 proof verified: |G_3|=120, Z(G_3)=1,")
    print("|G_3'|=60 (index 2), and G_3' is simple (class sizes 1,12,12,15,20,")
    print("no nontrivial proper divisor achievable as a union of classes).")


def verify_final_theorem(max_n=6):
    """Check |G_{m,n}| == mn! (i.e. full symmetric group) exactly when
    m>=3 or n>=4, for 2 <= m <= n <= max_n -- the claim of the final
    theorem in initial_3cycle.tex."""
    for n in range(2, max_n + 1):
        for m in range(2, n + 1):
            order, transitive, _ = group_order(m, n)
            full = order == factorial(m * n)
            expected_full = (m >= 3) or (n >= 4)
            status = "OK" if full == expected_full else "MISMATCH"
            print(f"{m}x{n}: |G|={order}  full={full}  expected_full={expected_full}  [{status}]")


if __name__ == "__main__":
    for rows, cols in [(2, 3), (2, 4), (3, 3)]:
        report(rows, cols)

    verify_2x4_elementary_proof()
    verify_g3_iso_s5()

    print("Verifying the final theorem (G_{m,n} = S_mn iff m>=3 or n>=4):")
    verify_final_theorem()
